// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"

	"github.com/jackc/pgtype"
)

type Budget struct {
	ID          int32          `json:"id"`
	Username    string         `json:"username"`
	ShopName    string         `json:"shop_name"`
	Category    string         `json:"category"`
	Price       pgtype.Numeric `json:"price"`
	ExpenseDate time.Time      `json:"expense_date"`
}

type Salary struct {
	ID        int32          `json:"id"`
	Username  string         `json:"username"`
	Salary    pgtype.Numeric `json:"salary"`
	StoreDate time.Time      `json:"store_date"`
}
